baseURL = "https://jaconsta.com/"
languageCode = "en-us"
title = "Jaconsta"


[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Whoami"
url = "/me/"

[[menu.main]]
weight = 3
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 4
name = "Portfolio"
identifier = "portfolio"
url = "/portfolio/"
  [[menu.main]]
  weight = 1
  name = "Catena"
  url = "/portfolio/catena"
  parent = "portfolio"
  [[menu.main]]
  weight = 2
  name = "Pomelo"
  url = "/portfolio/pomelo"
  parent = "portfolio"
  [[menu.main]]
  weight = 4
  name = "Webmarks"
  url = "/portfolio/webmarks"
  parent = "portfolio"
  [[menu.main]]
  weight = 5
  name = "Sentiment analysis"
  url = "/portfolio/sentiment_analysis"
  parent = "portfolio"
  [[menu.main]]
  weight = 6
  name = "Rest Book"
  url = "/portfolio/rest_book"
  parent = "portfolio"
  [[menu.main]]
  weight = 7
  name = "Creative labs"
  url = "/portfolio/fiboclock"
  parent = "portfolio"

[[menu.main]]
weight = 5
name = "Contact"
url = "/contact/"

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"
