baseURL = "https://jaconsta.com/"
languageCode = "en-us"
title = "Jaconsta"
theme = "crab"

[params]
description = "Developer, engineer, entrepreneur."
logoimage = "images/gecko_logo_r_120.png"
copyright = " - jaconsta _-_ CO _-_ © CC BY-NC 4.0"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Whoami"
url = "/me/"

[[menu.main]]
weight = 3
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 4
name = "Portfolio"
identifier = "portfolio"
url = "/portfolio/"
  [[menu.main]]
  weight = 1
  name = "Trimmer"
  url = "/portfolio/trimmer"
  parent = "portfolio"
  [[menu.main]]
  weight = 2
  name = "Pomelo"
  url = "/portfolio/pomelo"
  parent = "portfolio"
  [[menu.main]]
  weight = 3
  name = "Rest Book"
  url = "/portfolio/rest_book"
  parent = "portfolio"  
  [[menu.main]]
  weight = 4
  name = "Creative labs"
  url = "/portfolio/fiboclock"
  parent = "portfolio"

[[menu.main]]
weight = 5
name = "Contact"
url = "/contact/"

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"

